openapi: "3.0.0"
info:
  version: 1.0.0
  title: em-simple-login-api
  description: A Simple Login API to test with EvoMaster
servers:
  - url: https://simple-login.pgarrett.com
    description: Production URL
    
paths: {}