openapi: "3.0.0"
info:
  version: 1.0.0
  title: em-simple-login-api
  description: A Simple Login API to test with EvoMaster
servers:
  - url: https://simple-login.pgarrett.com
    description: Production URL
components:
  schemas:
    User:
      type: object
      properties:
        acccess_token:
          type: string
        name:
          type: string
        age:
          type: integer
          format: int64
    GeneralError:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
  responses:
    Unauthorized:
      description: Invalid username or password
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/GeneralError"
    InvalidToken:
      description: Invalid token
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/GeneralError"
paths: 
  /login:
    post:
      description: Login to the API
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        '401':
          description: Login failure
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GeneralError"
  /useMe:
    get:
      description: Use of the API with the provided token